//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrunhildeBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentKeyPhrases
    {
        public int KeyPhraseId { get; set; }
        public string Phrase { get; set; }
        public string RedditId { get; set; }
    
        public virtual Comments Comments { get; set; }
    }
}
